spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/local # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: 13.209.250.13:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true

app:
  topic:
    account:
      register-enterprise: register-enterprise
      register-labeler: register-labeler

  web-client:
    base-url: http://api.belloga.com # domain name